<a href="https://colab.research.google.com/github/VivXwan/PepDSNotes/blob/main/TensorFlow_ANN/TensorFlow_and_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. ANN Build,
2. How to select number of hidden layers and neurons,
3. Keras-Tuner (It is to DL as Randomized Search CV is to ML)

# TensorFlow

In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow version: {}".format(tf.__version__))

TensorFlow version: 2.8.0


In [3]:
print("Keras version: {}".format(tf.keras.__version__))

Keras version: 2.8.0


In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [8]:
k = tf.constant(42)

In [9]:
k

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [10]:
k = tf.constant(1,dtype = tf.int64)

In [11]:
k

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [12]:
a = tf.constant([[4,2],[9,5]])

In [13]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [14]:
b = tf.constant(a)

In [15]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [16]:
print(tf.ones(shape = (3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [17]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [18]:
a1 = tf.constant([[3,4,5],[3,4,5]])
a2 = tf.constant([[1,2,3,],[1,2,3]])

c = tf.add(a1,a2)

c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [19]:
tf.random.normal(shape = (2,2), mean = 0, stddev = 1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0959858 , -0.4525764 ],
       [ 0.11244816,  0.61965233]], dtype=float32)>

In [20]:
tf.random.uniform(shape = (2,2),minval = 0, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [8, 8]], dtype=int32)>

# ANN: